### ISSUE TITLE
Add constraint argument to simplify function

### ISSUE THREAD

**Issue by EmanuelGoncalves** [cdanielmachado/framed#22]
Hi,

Model _simplify_ function would benefit from having argument _constraints_:

`c_model = simplify(c_model, constraints=environmental_conditions, inplace=False)`

This would allow to retrieve a context-specific model without changing the original one.

Thanks,

**Comment by cdanielmachado** [comment]
Had forgotten about this... :)

I added the argument, it will come in the next release.
