### ISSUE TITLE
Several problems for DFBA

### ISSUE THREAD

**Issue by jinb88187** [cdanielmachado/framed#39]
Hi, I am exactly following dfba tutorial for batch fermentation. I have encountered many problems so far:

1- ImportError: cannot import name 'CONSTRAINT_BASED'

If I remove CONSTRAINT_BASED from the script, then I see this error when typing fix_cobra_model(ec_core_model):
2- AttributeError: 'Reaction' object has no attribute 'lb'

Removing fix_cobra_model(ec_core_model), I get this error:

3- AttributeError: 'Model' object has no attribute 'biomass_reaction'

Then, removing ec = Ecoli(ec_core_model, id='ecoli'), I get this error:

4- AttributeError: 'Model' object has no attribute 'update'
 This happens when it reaches to : result = dFBAm(bioreactor, t0, tf, dt, initial_conditions, solver, verbose)

I really need help and any advice is greatly appreciated. I have similar problems for fed-batch example.
Thanks

**Comment by cdanielmachado** [comment]
Hi, the `framed` library has been discontinued, we are not maintaining it anymore. It was replaced with `reframed` which no longer has DFBA. My suggestion is that you search the literature for the most recent DFBA implementation or contact the lab of Krishna Mahadevan for advice.
